server:
  port: 8203
spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yygh_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.52.100
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/yygh/user/mapper/xml/*.xml
wx:
  open:
    app-id: wxc606fb748aedee7c
    app-secret: 073e8e1117c1054b14586c8aa922bc9c
    redirect-uri: http://localhost:9001/api/user/wx/callback
#  # 微信开放平台 appid
#  wx.open.app-id=wxc606fb748aedee7c
#  # 微信开放平台 appsecret
#  wx.open.app-secret=073e8e1117c1054b14586c8aa922bc9c
#  # 微信开放平台 重定向url
#  wx.open.redirect-uri=http://localhost:9001/api/user/wx/callback
